<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260704051555 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dir (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BAAB7A10727ACA70 ON dir (parent_id)');
        $this->addSql('CREATE TABLE file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, dir_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C9F3610EEB38DE6 ON file (dir_id)');
        $this->addSql('ALTER TABLE dir ADD CONSTRAINT FK_BAAB7A10727ACA70 FOREIGN KEY (parent_id) REFERENCES dir (id)');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F3610EEB38DE6 FOREIGN KEY (dir_id) REFERENCES dir (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dir DROP CONSTRAINT FK_BAAB7A10727ACA70');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F3610EEB38DE6');
        $this->addSql('DROP TABLE dir');
        $this->addSql('DROP TABLE file');
    }
}
