<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260627112659 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE controller (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, method VARCHAR(255) NOT NULL, project_id INT NOT NULL, response_id INT DEFAULT NULL, file_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4CF2669A166D1F9C ON controller (project_id)');
        $this->addSql('CREATE INDEX IDX_4CF2669AFBF32840 ON controller (response_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4CF2669A93CB796C ON controller (file_id)');
        $this->addSql('CREATE TABLE directory (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, type VARCHAR(255) DEFAULT NULL, project_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_467844DA166D1F9C ON directory (project_id)');
        $this->addSql('CREATE INDEX IDX_467844DA727ACA70 ON directory (parent_id)');
        $this->addSql('CREATE TABLE field (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, php_type VARCHAR(255) NOT NULL, is_array BOOLEAN NOT NULL, is_nullable BOOLEAN NOT NULL, response_id INT NOT NULL, object_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5BF54558FBF32840 ON field (response_id)');
        $this->addSql('CREATE INDEX IDX_5BF54558232D562B ON field (object_id)');
        $this->addSql('CREATE TABLE file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, type VARCHAR(255) DEFAULT NULL, directory_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C9F36102C94069F ON file (directory_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE response (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, class_name VARCHAR(255) NOT NULL, filepath VARCHAR(255) NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3E7B0BFB166D1F9C ON response (project_id)');
        $this->addSql('ALTER TABLE controller ADD CONSTRAINT FK_4CF2669A166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE controller ADD CONSTRAINT FK_4CF2669AFBF32840 FOREIGN KEY (response_id) REFERENCES response (id)');
        $this->addSql('ALTER TABLE controller ADD CONSTRAINT FK_4CF2669A93CB796C FOREIGN KEY (file_id) REFERENCES file (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE directory ADD CONSTRAINT FK_467844DA166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE directory ADD CONSTRAINT FK_467844DA727ACA70 FOREIGN KEY (parent_id) REFERENCES directory (id)');
        $this->addSql('ALTER TABLE field ADD CONSTRAINT FK_5BF54558FBF32840 FOREIGN KEY (response_id) REFERENCES response (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE field ADD CONSTRAINT FK_5BF54558232D562B FOREIGN KEY (object_id) REFERENCES response (id)');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F36102C94069F FOREIGN KEY (directory_id) REFERENCES directory (id)');
        $this->addSql('ALTER TABLE response ADD CONSTRAINT FK_3E7B0BFB166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE controller DROP CONSTRAINT FK_4CF2669A166D1F9C');
        $this->addSql('ALTER TABLE controller DROP CONSTRAINT FK_4CF2669AFBF32840');
        $this->addSql('ALTER TABLE controller DROP CONSTRAINT FK_4CF2669A93CB796C');
        $this->addSql('ALTER TABLE directory DROP CONSTRAINT FK_467844DA166D1F9C');
        $this->addSql('ALTER TABLE directory DROP CONSTRAINT FK_467844DA727ACA70');
        $this->addSql('ALTER TABLE field DROP CONSTRAINT FK_5BF54558FBF32840');
        $this->addSql('ALTER TABLE field DROP CONSTRAINT FK_5BF54558232D562B');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F36102C94069F');
        $this->addSql('ALTER TABLE response DROP CONSTRAINT FK_3E7B0BFB166D1F9C');
        $this->addSql('DROP TABLE controller');
        $this->addSql('DROP TABLE directory');
        $this->addSql('DROP TABLE field');
        $this->addSql('DROP TABLE file');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE response');
    }
}
