<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260624152748 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE directory (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, project_id INT NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_467844DA166D1F9C ON directory (project_id)');
        $this->addSql('CREATE INDEX IDX_467844DA727ACA70 ON directory (parent_id)');
        $this->addSql('CREATE TABLE file (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, directory_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8C9F36102C94069F ON file (directory_id)');
        $this->addSql('ALTER TABLE directory ADD CONSTRAINT FK_467844DA166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE directory ADD CONSTRAINT FK_467844DA727ACA70 FOREIGN KEY (parent_id) REFERENCES directory (id)');
        $this->addSql('ALTER TABLE file ADD CONSTRAINT FK_8C9F36102C94069F FOREIGN KEY (directory_id) REFERENCES directory (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE directory DROP CONSTRAINT FK_467844DA166D1F9C');
        $this->addSql('ALTER TABLE directory DROP CONSTRAINT FK_467844DA727ACA70');
        $this->addSql('ALTER TABLE file DROP CONSTRAINT FK_8C9F36102C94069F');
        $this->addSql('DROP TABLE directory');
        $this->addSql('DROP TABLE file');
    }
}
