<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260616223515 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE field (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, is_array BOOLEAN NOT NULL, is_nullable BOOLEAN NOT NULL, response_id INT NOT NULL, object_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5BF54558FBF32840 ON field (response_id)');
        $this->addSql('CREATE INDEX IDX_5BF54558232D562B ON field (object_id)');
        $this->addSql('CREATE TABLE response (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, filepath VARCHAR(255) NOT NULL, project_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3E7B0BFB166D1F9C ON response (project_id)');
        $this->addSql('ALTER TABLE field ADD CONSTRAINT FK_5BF54558FBF32840 FOREIGN KEY (response_id) REFERENCES response (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE field ADD CONSTRAINT FK_5BF54558232D562B FOREIGN KEY (object_id) REFERENCES response (id)');
        $this->addSql('ALTER TABLE response ADD CONSTRAINT FK_3E7B0BFB166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE field DROP CONSTRAINT FK_5BF54558FBF32840');
        $this->addSql('ALTER TABLE field DROP CONSTRAINT FK_5BF54558232D562B');
        $this->addSql('ALTER TABLE response DROP CONSTRAINT FK_3E7B0BFB166D1F9C');
        $this->addSql('DROP TABLE field');
        $this->addSql('DROP TABLE response');
    }
}
